# load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "uniformlyrandom",
    hdrs = ["uniformlyrandom.h"],
    deps = [
        "//mvc/utils:point_cloud_set",
        "@parlaylib//parlay:primitives",
    ],
)
