# package(default_visibility = ["//:__subpackages__"])
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "uniformlyrandom",
    hdrs = ["uniformlyrandom.h"],
    deps = [
      "@parlaylib//parlay:primitives",
      "//mvc/utils:point_cloud_set",
    ],
)