dataset:
  name: infovqa
  path: data/vidore/infovqa
  results: results/vidore/infovqa

indices:
  - name: mvivf
    build_configs:
      - name: mvivf_500  # A unique, human-readable name for this build
        rebuild: false # True/False
        build_only: false # True/False
        params:
          k_per_level: 0 # Default 0: Avg num embs
          max_leaf_size: 500
        search_configs:
          - name: k=10 # Name for this specific search experiment
            # The script will generate the Cartesian product of all parameter lists here.
            append: false
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
              k: [10]
              config: 
                - {name: "", num_rerank: 0}
          - name: k=100
            append: false
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [100]
              config: 
                - {name: "", num_rerank: 0}

      - name: mvivf_500_pq_256_16
        rebuild: false
        build_only: false
        params:
          k_per_level: 0
          max_leaf_size: 500
          pq_enabled: true
          num_blocks: 8
          num_clusters_per_block: 256
        search_configs:
          - name: k=10
            append: false
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config: 
                - {name: "nr100", num_rerank: 100}
                - {name: "nr200", num_rerank: 200}
          - name: k=100
            append: false
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [100]
              config: 
                - {name: "nr1000", num_rerank: 1000}
                - {name: "nr2000", num_rerank: 2000}

  - name: muvera
    build_configs:
      - name: muvera_2560
        rebuild: false
        params:
          d_fde: 2560 # FDE dim [2560, 5120]
        search_configs:
          - name: k=10
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config: 
                - {name: "nr100", num_rerank: 100}
                - {name: "nr200", num_rerank: 200}
          - name: k=100
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [100]
              config: 
                - {name: "nr1000", num_rerank: 1000}
                - {name: "nr2000", num_rerank: 2000}
      - name: muvera_5120
        rebuild: false
        params:
          d_fde: 5120 # FDE dim [2560, 5120]
        search_configs:
          - name: k=10
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config: 
                - {name: "nr100", num_rerank: 100}
                - {name: "nr200", num_rerank: 200}
          - name: k=100
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [100]
              config: 
                - {name: "nr1000", num_rerank: 1000}
                - {name: "nr2000", num_rerank: 2000}

      - name: muvera_2560_pq_256_16
        rebuild: false
        params:
          d_fde: 2560 # FDE dim [2560, 5120]
          pq_enabled: true
          num_blocks: 160
          num_clusters_per_block: 256
        search_configs:
          - name: k=10
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config: 
                - {name: "nr100", num_rerank: 100}
                - {name: "nr1000", num_rerank: 1000}
          - name: k=100
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [100]
              config: 
                - {name: "nr1000", num_rerank: 1000}
                - {name: "nr2000", num_rerank: 2000}
      - name: muvera_5120_pq_256_16
        rebuild: false
        params:
          d_fde: 5120 # FDE dim [2560, 5120]
          pq_enabled: true
          num_blocks: 320
          num_clusters_per_block: 256
        search_configs:
          - name: k=10
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config: 
                - {name: "nr100", num_rerank: 100}
                - {name: "nr1000", num_rerank: 1000}
          - name: k=100
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [100]
              config: 
                - {name: "nr1000", num_rerank: 1000}
                - {name: "nr2000", num_rerank: 2000}

  # - name: mpool
  #   build_configs:
  #     - name: mpool
  #       rebuild: false
  #       params:
  #       search_configs:
  #         - name: k=10
  #           append: false
  #           params:
  #             L: [16, 32, 64, 128, 256, 512]
  #             k: [10]
  #             config: 
  #               - {name: "", num_rerank: 80}

  # - name: vamana
  #   build_configs:
  #     - name: vamana
  #       rebuild: false
  #       params:
  #       search_configs:
  #         - name: k=10
  #           append: false
  #           params:
  #             L: [16, 32, 64, 128, 256, 512]
  #             k: [10]
  #             config: 
  #               - {name: "", num_rerank: 0}

  # - name: fastplaid
  #   build_configs:
  #     - name: fastplaid
  #       rebuild: false
  #       params:
  #         nbits: 4
  #       search_configs:
  #         - name: k=10
  #           append: false
  #           params:
  #             n_ivf_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
  #             k: [10]
  #             config: 
  #               - {name: "", n_full_scores: 4096}