name: "Final Experiments - Quora (TurboQuant)"

datasets:
  - name: quora
    path: data/beir/quora
    results: results/final/quora

indices:
  - name: muvera
    build_configs:
      - name: muvera_2560_tq
        params:
          verbose: 1
          d_fde: 2560
          pq_method: 4
        search_configs:
          - name: k=10
            params: &L_tq
              L: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                - {name: "nr10", num_rerank: 10, norerank: True}
                - {name: "nr50", num_rerank: 50}
                - {name: "nr500", num_rerank: 500}
                - {name: "nr5000", num_rerank: 5000}

  - name: vamana
    build_configs:
      - name: vamana_R200_tq
        params:
          verbose: 1
          R: 200
          pq_method: 4
        search_configs:
          - name: k=10
            params:
              <<: *L_tq
              config:
                - {name: "nr10", num_rerank: 0}
                - {name: "nr20", num_rerank: 20}
                - {name: "nr50", num_rerank: 50}
                - {name: "nr100", num_rerank: 100}

  - name: svh_graph
    build_configs:
      - name: svh_graph_R200_tq
        params:
          verbose: 1
          R: 200
          pq_method: 4
        search_configs:
          - name: k=10
            params:
              <<: *L_tq
              config:
                - {name: "nr10", num_rerank: 10, norerank: True}
                - {name: "nr50", num_rerank: 50}
                - {name: "nr500", num_rerank: 500}
                - {name: "nr5000", num_rerank: 5000}
