name: "Final Experiments - FastPlaid BEIR5"

datasets:
  - name: nfcorpus
    path: data/beir/nfcorpus
    results: results/final/beir5/nfcorpus
  - name: scifact
    path: data/beir/scifact
    results: results/final/beir5/scifact
  - name: arguana
    path: data/beir/arguana
    results: results/final/beir5/arguana
  - name: scidocs
    path: data/beir/scidocs
    results: results/final/beir5/scidocs
  - name: fiqa
    path: data/beir/fiqa
    results: results/final/beir5/fiqa

indices:
  - name: fastplaid
    build_configs:
      - name: fastplaid_nbits4
        params:
          nbits: 4
        search_configs:
          - name: k=10
            params:
              n_ivf_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
              k: [10]
              config:
                - {name: "nr1024", num_rerank: 1024}
                - {name: "nr4096", num_rerank: 4096}
                - {name: "nr8192", num_rerank: 8192}
