dataset:
  name: arguana
  path: data/beir/arguana
  results: results/beir/arguana

k: 10

results:
  - ["mvivf", "mvivf_500", ""]
  - ["mvivf", "mvivf_500_pq_256_16", "nr100"]
  - ["muvera", "muvera_2560", "nr100"]
