#!/usr/bin/env python3
"""Generate the TU-split scaffolding for the `bench` (single-shot build+search)
binary:

  bench_run_one_decl.h   — lightweight: BenchRunOneCtx + bench_run_one decl,
                           no mvivf*.h or quantizer headers (included by
                           bench_impl.h and per-cell .cc TUs).
  bench_inst.h           — heavy: pulls every variant + quantizer header and
                           declares all extern templates (included only by
                           the dispatch TU bench.cpp).
  bench_inst/<cell>.cc   — 96 files, one per (metric × variant × quantizer ×
                           compress). Each TU includes bench_impl.h + ONE
                           variant header + ONE quantizer header, then
                           explicitly instantiates exactly one specialization
                           of bench_run_one. Splitting compress=false and
                           compress=true into separate TUs lets all 96 run
                           in parallel; wall-clock = max single-cell
                           instantiation time (~60s on this codebase).

Run from anywhere:
    python3 mvsic/mvivf/gen_bench_inst.py

The generator is the source of truth; commit its output. To add a new
quantizer or variant, edit METRICS / VARIANTS / QUANTS below and rerun.
The dispatch logic in bench.cpp must be updated separately.
"""
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
INST_DIR = os.path.join(ROOT, "bench_inst")
DECL_PATH = os.path.join(ROOT, "bench_run_one_decl.h")
HEADER_PATH = os.path.join(ROOT, "bench_inst.h")

# (tag, ChPoint type, metric value as C++ literal, ChPoint header)
METRICS = [
    ("ip", "ChamferIP_Point", "false", "mvsic/core/types/chamfer_ip_point.h"),
    ("l2", "ChamferL2_Point", "true",  "mvsic/core/types/chamfer_l2_point.h"),
]

# (tag, family template, header)
VARIANTS = [
    ("regular", "IndexMVIVF",      "mvsic/mvivf/mvivf.h"),
    ("flat",    "IndexMVIVFFlat",  "mvsic/mvivf/mvivf_flat.h"),
    ("spill",   "IndexMVIVFSpill", "mvsic/mvivf/mvivf_spill.h"),
]

# (tag, model template — {m} substitutes the metric literal, header or None
# for NoQuantizer which already comes via the variant header through index.h)
QUANTS = [
    ("none",  "NoQuantizer<{m}>",                  None),
    ("pq",    "pq_mv::Model<{m}>",                 "mvsic/core/quantization/pq_mv.h"),
    ("fs",    "fastscan_mv::Model<{m}>",           "mvsic/core/quantization/fastscan_mv.h"),
    ("rq",    "rabitq_mv::Model<{m}>",             "mvsic/core/quantization/rabitq_mv.h"),
    ("tq",    "turboquant_mv::Model<{m}>",         "mvsic/core/quantization/turboquant_mv.h"),
    ("spqtq", "pqtq_mv::Model<{m}>",               "mvsic/core/quantization/pqtq_mv.h"),
    ("1btq",  "turboquant_1bit_mv::Model<{m}>",    "mvsic/core/quantization/turboquant_1bit_mv.h"),
    ("8btq",  "turboquant_8bit_mv::Model<{m}>",    "mvsic/core/quantization/turboquant_8bit_mv.h"),
]

CC_TEMPLATE = """\
// GENERATED by gen_bench_inst.py. Do not edit.
#include "mvsic/mvivf/bench_impl.h"
#include "{ChPointHeader}"
#include "{VariantHeader}"
{QuantInclude}

namespace mvsic {{
namespace bench_main {{
template void bench_run_one<{ChPoint}, {m}, {Fam}<{m}, {Compress}, {Model}>>(
    BenchRunOneCtx<{ChPoint}>&);
}}  // namespace bench_main
}}  // namespace mvsic
"""

DECL_HEADER = """\
#pragma once
// GENERATED by gen_bench_inst.py. Do not edit.
//
// Lightweight forward-decls for bench_run_one. Pulls in IndexParams /
// SearchParams (value members of BenchRunOneCtx) but **not** any mvivf*.h
// or quantizer headers. Included by bench_impl.h and the per-cell
// instantiation TUs so each TU only parses the variant + quantizer headers
// it actually instantiates against.

#include <cstddef>
#include <string>

#include "mvsic/core/index_params.h"
#include "mvsic/core/search_params.h"

namespace mvsic {

template <typename> class PointCloudSet;

namespace bench_main {

enum class MVIVFVariant { Regular, Flat, Spill };

template <typename ChPoint>
struct BenchRunOneCtx {
  PointCloudSet<ChPoint>* points;
  IndexParams index_params;
  SearchParams search_params;
  std::string out_file;
  std::string index_file;
  std::string q_file;
  std::string gt_file;
  MVIVFVariant variant;
  bool compress_centers;
  std::string quant_method;
  std::size_t k;
};

template <typename ChPoint, bool metric, class IndexT>
void bench_run_one(BenchRunOneCtx<ChPoint>& ctx);

}  // namespace bench_main
}  // namespace mvsic
"""

HEADER_PRELUDE = """\
#pragma once
// GENERATED by gen_bench_inst.py. Do not edit.
//
// Heavy header: included only by the dispatch TU (bench.cpp). Pulls every
// variant + quantizer header so the dispatch macros can name the types, and
// declares extern templates for every (metric, variant, quantizer, compress)
// cell so the dispatch TU does not pay to instantiate them. The definitions
// live in bench_impl.h and are explicitly instantiated once per cell under
// bench_inst/.

#include "mvsic/mvivf/bench_run_one_decl.h"

#include "mvsic/core/quantization/fastscan_mv.h"
#include "mvsic/core/quantization/pq_mv.h"
#include "mvsic/core/quantization/pqtq_mv.h"
#include "mvsic/core/quantization/rabitq_mv.h"
#include "mvsic/core/quantization/turboquant_1bit_mv.h"
#include "mvsic/core/quantization/turboquant_8bit_mv.h"
#include "mvsic/core/quantization/turboquant_mv.h"
#include "mvsic/core/types/chamfer_ip_point.h"
#include "mvsic/core/types/chamfer_l2_point.h"
#include "mvsic/core/types/point_cloud_set.h"
#include "mvsic/mvivf/mvivf.h"
#include "mvsic/mvivf/mvivf_flat.h"
#include "mvsic/mvivf/mvivf_spill.h"

namespace mvsic {
namespace bench_main {

"""

HEADER_EPILOGUE = """\

}  // namespace bench_main
}  // namespace mvsic
"""


def main():
    os.makedirs(INST_DIR, exist_ok=True)

    with open(DECL_PATH, "w") as f:
        f.write(DECL_HEADER)

    written_cc = []
    for metric_tag, ChPoint, m, ChPointHeader in METRICS:
        for variant_tag, Fam, VariantHeader in VARIANTS:
            for quant_tag, Model_tmpl, QuantHeader in QUANTS:
                Model = Model_tmpl.format(m=m)
                qinc = f'#include "{QuantHeader}"' if QuantHeader else ""
                for compress_tag, Compress in (("nc", "false"), ("c", "true")):
                    fn = f"{metric_tag}_{variant_tag}_{quant_tag}_{compress_tag}.cc"
                    path = os.path.join(INST_DIR, fn)
                    with open(path, "w") as f:
                        f.write(CC_TEMPLATE.format(
                            ChPoint=ChPoint, m=m, Fam=Fam, Model=Model,
                            Compress=Compress,
                            ChPointHeader=ChPointHeader,
                            VariantHeader=VariantHeader,
                            QuantInclude=qinc))
                    written_cc.append(fn)

    decls = []
    for metric_tag, ChPoint, m, _ in METRICS:
        for variant_tag, Fam, _ in VARIANTS:
            for quant_tag, Model_tmpl, _ in QUANTS:
                Model = Model_tmpl.format(m=m)
                for c in ("false", "true "):
                    decls.append(
                        f"extern template void bench_run_one<{ChPoint}, {m}, "
                        f"{Fam}<{m}, {c}, {Model}>>(BenchRunOneCtx<{ChPoint}>&);"
                    )
    with open(HEADER_PATH, "w") as f:
        f.write(HEADER_PRELUDE)
        f.write("\n".join(decls))
        f.write("\n")
        f.write(HEADER_EPILOGUE)

    print(f"Wrote {DECL_PATH}")
    print(f"Wrote {HEADER_PATH}")
    print(f"Wrote {len(written_cc)} .cc files under {INST_DIR}/")


if __name__ == "__main__":
    main()
