#pragma once

// TurboQuant: two-stage vector quantization for near-optimal MSE and unbiased inner product
// (TurboQuant: Online Vector Quantization with Near-optimal Distortion Rate,
// arxiv.org/abs/2504.19874). Stage 1 (MSE): random rotation (e.g. FHT) + per-coordinate scalar
// quantization (scale/offset). Stage 2 (inner product): 1-bit QJL on residual r = x_rot -
// decode(base) for unbiased <q,x> estimate. Inner product: <q,x> ≈ base_ip + (sqrt(pi/2)/m) *
// sum_k sign(<g_k,r>) * <q,g_k>, with random g_k.
// Stage 1 uses Lloyd-Max quantization for N(0,1) (optimal MSE, uncorrelated residual for QJL).

#include <immintrin.h>
#include <Eigen/Core>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <limits>
#include <memory>
#include <random>
#include <type_traits>
#include <vector>

#include "parlay/parallel.h"
#include "parlay/sequence.h"

// Optional: define TURBOQUANT_USE_IDENTITY_ROTATION to skip rabitqlib rotator (no rotation).
// Use when the library rotator crashes; quality will be lower but the pipeline runs.
#if !defined(TURBOQUANT_USE_IDENTITY_ROTATION)
#include "rabitqlib/utils/rotator.hpp"
#endif

namespace mvsic {
namespace turboquant_naive {

// Pre-computed Lloyd-Max quantizer for N(0,1), 8-bit (256 levels). Generated by
// lloyd_max_gaussian_256.py.
namespace {
static const float kLloydMaxThresholds[255] = {
    -3.24923634f, -2.82879103f, -2.55469426f, -2.35514667f, -2.20300816f, -2.08380060f,
    -1.98826124f, -1.90989591f, -1.84400106f, -1.78717678f, -1.73700875f, -1.69181684f,
    -1.65044726f, -1.61210766f, -1.57624523f, -1.54246279f, -1.51046429f, -1.48002083f,
    -1.45094973f, -1.42310154f, -1.39635163f, -1.37059455f, -1.34574004f, -1.32171009f,
    -1.29843673f, -1.27586033f, -1.25392819f, -1.23259354f, -1.21181459f, -1.19155388f,
    -1.17177765f, -1.15245537f, -1.13355934f, -1.11506430f, -1.09694721f, -1.07918692f,
    -1.06176402f, -1.04466063f, -1.02786021f, -1.01134747f, -0.99510824f, -0.97912931f,
    -0.96339841f, -0.94790407f, -0.93263558f, -0.91758291f, -0.90273665f, -0.88808796f,
    -0.87362853f, -0.85935052f, -0.84524656f, -0.83130965f, -0.81753321f, -0.80391098f,
    -0.79043705f, -0.77710578f, -0.76391185f, -0.75085017f, -0.73791590f, -0.72510445f,
    -0.71241140f, -0.69983257f, -0.68736394f, -0.67500167f, -0.66274209f, -0.65058169f,
    -0.63851708f, -0.62654502f, -0.61466241f, -0.60286625f, -0.59115366f, -0.57952187f,
    -0.56796821f, -0.55649012f, -0.54508509f, -0.53375074f, -0.52248475f, -0.51128488f,
    -0.50014896f, -0.48907490f, -0.47806065f, -0.46710426f, -0.45620380f, -0.44535742f,
    -0.43456332f, -0.42381974f, -0.41312499f, -0.40247740f, -0.39187535f, -0.38131728f,
    -0.37080165f, -0.36032696f, -0.34989175f, -0.33949458f, -0.32913408f, -0.31880886f,
    -0.30851760f, -0.29825898f, -0.28803173f, -0.27783458f, -0.26766630f, -0.25752568f,
    -0.24741153f, -0.23732268f, -0.22725798f, -0.21721630f, -0.20719651f, -0.19719753f,
    -0.18721827f, -0.17725766f, -0.16731463f, -0.15738816f, -0.14747719f, -0.13758073f,
    -0.12769774f, -0.11782724f, -0.10796823f, -0.09811972f, -0.08828074f, -0.07845031f,
    -0.06862748f, -0.05881127f, -0.04900074f, -0.03919493f, -0.02939290f, -0.01959370f,
    -0.00979638f, 0.00000000f,  0.00979638f,  0.01959370f,  0.02939290f,  0.03919493f,
    0.04900074f,  0.05881127f,  0.06862748f,  0.07845031f,  0.08828074f,  0.09811972f,
    0.10796823f,  0.11782724f,  0.12769774f,  0.13758073f,  0.14747719f,  0.15738816f,
    0.16731463f,  0.17725766f,  0.18721827f,  0.19719753f,  0.20719651f,  0.21721630f,
    0.22725798f,  0.23732268f,  0.24741153f,  0.25752568f,  0.26766630f,  0.27783458f,
    0.28803173f,  0.29825898f,  0.30851760f,  0.31880886f,  0.32913408f,  0.33949458f,
    0.34989175f,  0.36032696f,  0.37080165f,  0.38131728f,  0.39187535f,  0.40247740f,
    0.41312499f,  0.42381974f,  0.43456332f,  0.44535742f,  0.45620380f,  0.46710426f,
    0.47806065f,  0.48907490f,  0.50014896f,  0.51128488f,  0.52248475f,  0.53375074f,
    0.54508509f,  0.55649012f,  0.56796821f,  0.57952187f,  0.59115366f,  0.60286625f,
    0.61466241f,  0.62654502f,  0.63851708f,  0.65058169f,  0.66274209f,  0.67500167f,
    0.68736394f,  0.69983257f,  0.71241140f,  0.72510445f,  0.73791590f,  0.75085017f,
    0.76391185f,  0.77710578f,  0.79043705f,  0.80391098f,  0.81753321f,  0.83130965f,
    0.84524656f,  0.85935052f,  0.87362853f,  0.88808796f,  0.90273665f,  0.91758291f,
    0.93263558f,  0.94790407f,  0.96339841f,  0.97912931f,  0.99510824f,  1.01134747f,
    1.02786021f,  1.04466063f,  1.06176402f,  1.07918692f,  1.09694721f,  1.11506430f,
    1.13355934f,  1.15245537f,  1.17177765f,  1.19155388f,  1.21181459f,  1.23259354f,
    1.25392819f,  1.27586033f,  1.29843673f,  1.32171009f,  1.34574004f,  1.37059455f,
    1.39635163f,  1.42310154f,  1.45094973f,  1.48002083f,  1.51046429f,  1.54246279f,
    1.57624523f,  1.61210766f,  1.65044726f,  1.69181684f,  1.73700875f,  1.78717678f,
    1.84400106f,  1.90989591f,  1.98826124f,  2.08380060f,  2.20300816f,  2.35514667f,
    2.55469426f,  2.82879103f,  3.24923634f};
static const float kLloydMaxCentroids[256] = {
    -3.50945761f, -2.98901507f, -2.66856699f, -2.44082153f, -2.26947180f, -2.13654452f,
    -2.03105668f, -1.94546581f, -1.87432601f, -1.81367610f, -1.76067746f, -1.71334004f,
    -1.67029364f, -1.63060089f, -1.59361444f, -1.55887602f, -1.52604955f, -1.49487902f,
    -1.46516263f, -1.43673683f, -1.40946625f, -1.38323701f, -1.35795209f, -1.33352798f,
    -1.30989219f, -1.28698128f, -1.26473938f, -1.24311701f, -1.22207007f, -1.20155911f,
    -1.18154865f, -1.16200665f, -1.14290409f, -1.12421458f, -1.10591402f, -1.08798039f,
    -1.07039345f, -1.05313460f, -1.03618666f, -1.01953376f, -1.00316119f, -0.98705529f,
    -0.97120334f, -0.95559348f, -0.94021466f, -0.92505651f, -0.91010932f, -0.89536398f,
    -0.88081194f, -0.86644512f, -0.85225593f, -0.83823718f, -0.82438212f, -0.81068430f,
    -0.79713766f, -0.78373643f, -0.77047514f, -0.75734857f, -0.74435177f, -0.73148004f,
    -0.71872886f, -0.70609394f, -0.69357119f, -0.68115668f, -0.66884666f, -0.65663753f,
    -0.64452585f, -0.63250831f, -0.62058174f, -0.60874308f, -0.59698941f, -0.58531791f,
    -0.57372584f, -0.56221059f, -0.55076964f, -0.53940054f, -0.52810094f, -0.51686856f,
    -0.50570120f, -0.49459673f, -0.48355307f, -0.47256824f, -0.46164028f, -0.45076732f,
    -0.43994752f, -0.42917911f, -0.41846037f, -0.40778961f, -0.39716519f, -0.38658552f,
    -0.37604905f, -0.36555425f, -0.35509966f, -0.34468383f, -0.33430534f, -0.32396282f,
    -0.31365491f, -0.30338029f, -0.29313767f, -0.28292578f, -0.27274337f, -0.26258922f,
    -0.25246213f, -0.24236093f, -0.23228444f, -0.22223152f, -0.21220107f, -0.20219196f,
    -0.19220311f, -0.18223343f, -0.17228188f, -0.16234739f, -0.15242892f, -0.14252546f,
    -0.13263599f, -0.12275950f, -0.11289499f, -0.10304147f, -0.09319797f, -0.08336351f,
    -0.07353712f, -0.06371784f, -0.05390471f, -0.04409678f, -0.03429309f, -0.02449271f,
    -0.01469468f, -0.00489807f, 0.00489807f,  0.01469468f,  0.02449271f,  0.03429309f,
    0.04409678f,  0.05390471f,  0.06371784f,  0.07353712f,  0.08336351f,  0.09319797f,
    0.10304147f,  0.11289499f,  0.12275950f,  0.13263599f,  0.14252546f,  0.15242892f,
    0.16234739f,  0.17228188f,  0.18223343f,  0.19220311f,  0.20219196f,  0.21220107f,
    0.22223152f,  0.23228444f,  0.24236093f,  0.25246213f,  0.26258922f,  0.27274337f,
    0.28292578f,  0.29313767f,  0.30338029f,  0.31365491f,  0.32396282f,  0.33430534f,
    0.34468383f,  0.35509966f,  0.36555425f,  0.37604905f,  0.38658552f,  0.39716519f,
    0.40778961f,  0.41846037f,  0.42917911f,  0.43994752f,  0.45076732f,  0.46164028f,
    0.47256824f,  0.48355307f,  0.49459673f,  0.50570120f,  0.51686856f,  0.52810094f,
    0.53940054f,  0.55076964f,  0.56221059f,  0.57372584f,  0.58531791f,  0.59698941f,
    0.60874308f,  0.62058174f,  0.63250831f,  0.64452585f,  0.65663753f,  0.66884666f,
    0.68115668f,  0.69357119f,  0.70609394f,  0.71872886f,  0.73148004f,  0.74435177f,
    0.75734857f,  0.77047514f,  0.78373643f,  0.79713766f,  0.81068430f,  0.82438212f,
    0.83823718f,  0.85225593f,  0.86644512f,  0.88081194f,  0.89536398f,  0.91010932f,
    0.92505651f,  0.94021466f,  0.95559348f,  0.97120334f,  0.98705529f,  1.00316119f,
    1.01953376f,  1.03618666f,  1.05313460f,  1.07039345f,  1.08798039f,  1.10591402f,
    1.12421458f,  1.14290409f,  1.16200665f,  1.18154865f,  1.20155911f,  1.22207007f,
    1.24311701f,  1.26473938f,  1.28698128f,  1.30989219f,  1.33352798f,  1.35795209f,
    1.38323701f,  1.40946625f,  1.43673683f,  1.46516263f,  1.49487902f,  1.52604955f,
    1.55887602f,  1.59361444f,  1.63060089f,  1.67029364f,  1.71334004f,  1.76067746f,
    1.81367610f,  1.87432601f,  1.94546581f,  2.03105668f,  2.13654452f,  2.26947180f,
    2.44082153f,  2.66856699f,  2.98901507f,  3.50945761f};
}  // namespace

template<bool Metric>
class Quantized_Point;

template<bool Metric>
class Quantized_Query {
 public:
  using distanceType = float;

  // LUT for Stage 1 base IP: base_lut[d*256 + c] = q_rot[d] * kLloydMaxCentroids[c] * sigma
  std::vector<float> base_lut;
  std::vector<float> q_qjl;
  size_t dim = 0;
  size_t qjl_dim = 0;

  Quantized_Query() = default;
  Quantized_Query(size_t d, size_t m) : dim(d), qjl_dim(m) {
    base_lut.resize(d * 256);
    q_qjl.resize(m);
  }

  inline float distance(const Quantized_Point<Metric>& p) const;

  template<typename EncRange>
  void distances_all(const EncRange& db, float* out) const {
    const size_t N = (db.n_points_raw_unpadded != 0) ? db.n_points_raw_unpadded : db.n_points_raw;
    if (N == 0) return;

    const size_t d = dim;
    const size_t m = qjl_dim;
    const size_t m_bytes = (m + 7) / 8;
    const size_t stride = d + m_bytes + sizeof(float);

    const float* lut = base_lut.data();
    const float* q_j = q_qjl.data();
    const float qjl_const = std::sqrt(M_PI / 2.0) / static_cast<float>(m);

    parlay::parallel_for(
        0, N,
        [&](size_t i) {
          const uint8_t* ptr = db.packed_codes.data() + i * stride;
          if (i + 4 < N) __builtin_prefetch(db.packed_codes.data() + (i + 4) * stride, 0, 1);
          const uint8_t* base_ptr = ptr;
          const uint8_t* qjl_ptr = ptr + d;
          float norm_r;
          std::memcpy(&norm_r, ptr + d + m_bytes, sizeof(float));

          // Stage 1 base IP via Lloyd-Max LUT: base_ip = sum_d base_lut[d*256 + base_ptr[d]]
          float base_ip = 0.0f;
          for (size_t j = 0; j < d; ++j) {
            base_ip += lut[j * 256 + base_ptr[j]];
          }

          // Optimized QJL inner product: process byte-aligned chunks with SIMD
          float qjl_ip = 0.0f;
          size_t k = 0;
#if defined(__AVX2__)
          // 8 bits at a time; unpack fully in registers to avoid store-to-load stalls.
          __m256 sum_acc = _mm256_setzero_ps();
          const __m256i shifts = _mm256_setr_epi32(0, 1, 2, 3, 4, 5, 6, 7);
          const __m256i ones_i = _mm256_set1_epi32(1);
          // Scalar: sign_bit ? +q_j[k] : -q_j[k], so mult = -1 + 2*bit (bit 1 -> +1, bit 0 -> -1).
          const __m256 neg_one_f = _mm256_set1_ps(-1.0f);
          const __m256 two_f = _mm256_set1_ps(2.0f);

          for (; k + 8 <= m; k += 8) {
            const uint8_t byte_val = qjl_ptr[k >> 3];
            const __m256 q_vals = _mm256_loadu_ps(&q_j[k]);

            const __m256i byte_i = _mm256_set1_epi32(static_cast<int>(byte_val));
            const __m256i bits_i = _mm256_and_si256(_mm256_srlv_epi32(byte_i, shifts), ones_i);
            const __m256 bits_f = _mm256_cvtepi32_ps(bits_i);
            const __m256 mult = _mm256_add_ps(neg_one_f, _mm256_mul_ps(two_f, bits_f));

            sum_acc = _mm256_add_ps(sum_acc, _mm256_mul_ps(q_vals, mult));
          }

          alignas(32) float tmp_qjl[8];
          _mm256_store_ps(tmp_qjl, sum_acc);
          for (int ii = 0; ii < 8; ++ii)
            qjl_ip += tmp_qjl[ii];
#endif

          // Scalar fallback for remaining bits
          for (; k < m; ++k) {
            bool sign_bit = (qjl_ptr[k >> 3] >> (k & 7)) & 1;
            qjl_ip += sign_bit ? q_j[k] : -q_j[k];
          }

          float total_ip = base_ip + qjl_const * norm_r * qjl_ip;
          // NN sort ascending: smaller = closer. For IP, larger inner product = closer, so return
          // -total_ip.
          out[i] = -total_ip;
        },
        256);
  }
};

template<bool Metric>
class Quantized_Point {
 public:
  const uint8_t* code_ptr = nullptr;
  size_t dim = 0;
  size_t qjl_dim = 0;

  Quantized_Point() = default;
  Quantized_Point(const uint8_t* ptr, size_t d, size_t m) : code_ptr(ptr), dim(d), qjl_dim(m) {}

  inline float distance(const Quantized_Query<Metric>& qq) const {
    const size_t d = dim;
    const size_t m = qjl_dim;
    const size_t m_bytes = (m + 7) / 8;

    const uint8_t* base_ptr = code_ptr;
    const uint8_t* qjl_ptr = code_ptr + d;
    float norm_r;
    std::memcpy(&norm_r, code_ptr + d + m_bytes, sizeof(float));

    const float* lut = qq.base_lut.data();
    float base_ip = 0.0f;
    for (size_t j = 0; j < d; ++j) {
      base_ip += lut[j * 256 + base_ptr[j]];
    }

    // Optimized QJL inner product: process byte-aligned chunks with SIMD
    float qjl_ip = 0.0f;
    const float* q_j = qq.q_qjl.data();
    size_t k = 0;

#if defined(__AVX2__)
    __m256 sum_acc = _mm256_setzero_ps();
    const __m256i shifts = _mm256_setr_epi32(0, 1, 2, 3, 4, 5, 6, 7);
    const __m256i ones_i = _mm256_set1_epi32(1);
    // Scalar: sign_bit ? +q_j[k] : -q_j[k], so mult = -1 + 2*bit (bit 1 -> +1, bit 0 -> -1).
    const __m256 neg_one_f = _mm256_set1_ps(-1.0f);
    const __m256 two_f = _mm256_set1_ps(2.0f);

    for (; k + 8 <= m; k += 8) {
      const uint8_t byte_val = qjl_ptr[k >> 3];
      const __m256 q_vals = _mm256_loadu_ps(&q_j[k]);

      const __m256i byte_i = _mm256_set1_epi32(static_cast<int>(byte_val));
      const __m256i bits_i = _mm256_and_si256(_mm256_srlv_epi32(byte_i, shifts), ones_i);
      const __m256 bits_f = _mm256_cvtepi32_ps(bits_i);
      const __m256 mult = _mm256_add_ps(neg_one_f, _mm256_mul_ps(two_f, bits_f));
      sum_acc = _mm256_add_ps(sum_acc, _mm256_mul_ps(q_vals, mult));
    }

    // Horizontal sum
    alignas(32) float tmp_qjl[8];
    _mm256_store_ps(tmp_qjl, sum_acc);
    for (int i = 0; i < 8; ++i)
      qjl_ip += tmp_qjl[i];
#endif

    // Scalar fallback for remaining bits
    for (; k < m; ++k) {
      bool sign_bit = (qjl_ptr[k >> 3] >> (k & 7)) & 1;
      qjl_ip += sign_bit ? q_j[k] : -q_j[k];
    }

    const float qjl_const = std::sqrt(M_PI / 2.0) / static_cast<float>(m);
    float total_ip = base_ip + qjl_const * norm_r * qjl_ip;
    // NN sort ascending: smaller = closer. For IP, larger inner product = closer, so return
    // -total_ip.
    return -total_ip;
  }

  void prefetch() const {
    __builtin_prefetch(code_ptr, 0, 3);
  }
  bool same_as(const Quantized_Point<Metric>&) const {
    return false;
  }
  bool same_as(const Quantized_Query<Metric>&) const {
    return false;
  }
  bool is_metric() const {
    return Metric;
  }
};

template<bool Metric>
inline float Quantized_Query<Metric>::distance(const Quantized_Point<Metric>& p) const {
  return p.distance(*this);
}

template<typename PointRange, bool Metric>
class Quantized_Point_Range {
 public:
  static constexpr bool is_fastscan = false;

  size_t n_points_raw = 0;
  size_t n_points_raw_unpadded = 0;
  size_t dim = 0;
  size_t qjl_dim = 0;

  parlay::sequence<uint8_t> packed_codes;
  parlay::sequence<size_t> cloud_vec_offsets;

  Quantized_Point_Range() = default;

  Quantized_Point<Metric> operator[](size_t i) const {
    const size_t stride = dim + (qjl_dim + 7) / 8 + sizeof(float);
    return Quantized_Point<Metric>(&packed_codes[i * stride], dim, qjl_dim);
  }

  void save(std::ostream& out) const {
    out.write(reinterpret_cast<const char*>(&n_points_raw), sizeof(n_points_raw));
    out.write(reinterpret_cast<const char*>(&n_points_raw_unpadded), sizeof(n_points_raw_unpadded));
    out.write(reinterpret_cast<const char*>(&dim), sizeof(dim));
    out.write(reinterpret_cast<const char*>(&qjl_dim), sizeof(qjl_dim));

    size_t n_off = cloud_vec_offsets.size();
    out.write(reinterpret_cast<const char*>(&n_off), sizeof(n_off));
    if (n_off)
      out.write(reinterpret_cast<const char*>(cloud_vec_offsets.data()), n_off * sizeof(size_t));

    size_t sz = packed_codes.size();
    out.write(reinterpret_cast<const char*>(&sz), sizeof(sz));
    if (sz) out.write(reinterpret_cast<const char*>(packed_codes.data()), sz * sizeof(uint8_t));
  }

  void load(std::istream& in) {
    in.read(reinterpret_cast<char*>(&n_points_raw), sizeof(n_points_raw));
    in.read(reinterpret_cast<char*>(&n_points_raw_unpadded), sizeof(n_points_raw_unpadded));
    in.read(reinterpret_cast<char*>(&dim), sizeof(dim));
    in.read(reinterpret_cast<char*>(&qjl_dim), sizeof(qjl_dim));

    size_t n_off = 0;
    in.read(reinterpret_cast<char*>(&n_off), sizeof(n_off));
    cloud_vec_offsets.resize(n_off);
    if (n_off) in.read(reinterpret_cast<char*>(cloud_vec_offsets.data()), n_off * sizeof(size_t));

    size_t sz = 0;
    in.read(reinterpret_cast<char*>(&sz), sizeof(sz));
    packed_codes.resize(sz);
    if (sz) in.read(reinterpret_cast<char*>(packed_codes.data()), sz * sizeof(uint8_t));
  }

  inline uint32_t size() const noexcept { return static_cast<uint32_t>(n_points_raw_unpadded); }
  inline uint32_t get_dims() const noexcept { return static_cast<uint32_t>(dim); }
};

template<bool Metric>
class Model {
 public:
  static constexpr bool is_fastscan = false;

  size_t dim = 0;
  size_t padded_dim = 0;
  size_t qjl_dim = 0;

  float sigma = 1.0f;  // Global std dev of rotated data (N(0, sigma^2)); Lloyd-Max is for N(0,1)
  float global_mean = 0.0f;  // Center for Lloyd-Max (rotated data may have DC offset)
  std::vector<float> qjl_matrix;

#if defined(TURBOQUANT_USE_IDENTITY_ROTATION)
  bool use_identity_rotation_ = true;
  // no external rotator
#else
  bool use_identity_rotation_ = false;
  rabitqlib::RotatorType rotator_type = rabitqlib::RotatorType::FhtKacRotator;
  std::unique_ptr<rabitqlib::Rotator<float>> rotator;
#endif

  Model() = default;

  template<typename PointRange>
  Model(const PointRange& train_data, size_t q_dim = 0) {
    train(train_data, q_dim);
  }

  template<typename PointRange>
  void train(const PointRange& data, size_t q_dim = 0) {
    dim = data.get_dims();
    if (dim == 0) return;
#if defined(TURBOQUANT_USE_IDENTITY_ROTATION)
    padded_dim = dim;
#else
    rotator.reset(rabitqlib::choose_rotator<float>(dim, rotator_type));
    if (!rotator) return;
    padded_dim = rotator->size();
#endif
    qjl_dim = (q_dim == 0) ? padded_dim : q_dim;

    qjl_matrix.resize(qjl_dim * padded_dim);

    std::mt19937 gen(42);
    std::normal_distribution<float> dist(0.0f, 1.0f);
    for (size_t i = 0; i < qjl_dim * padded_dim; ++i) {
      qjl_matrix[i] = dist(gen);
    }

    const size_t n = data.size();
    const size_t sample_size = std::min(n, static_cast<size_t>(10000));
    if (sample_size == 0) return;

    // Compute global standard deviation of rotated data (CLT -> N(0, sigma^2))
    double sum = 0.0, sum_sq = 0.0;
    size_t count = 0;
    std::vector<float> p_rot(padded_dim);
    for (size_t i = 0; i < sample_size; ++i) {
      const float* p = reinterpret_cast<const float*>(data.location(i));
#if defined(TURBOQUANT_USE_IDENTITY_ROTATION)
      std::memcpy(p_rot.data(), p, dim * sizeof(float));
      for (size_t d = dim; d < padded_dim; ++d)
        p_rot[d] = 0.0f;
#else
      rotator->rotate(p, p_rot.data());
#endif
      for (size_t d = 0; d < padded_dim; ++d) {
        float v = p_rot[d];
        sum += v;
        sum_sq += static_cast<double>(v) * v;
        ++count;
      }
    }
    double mean = (count > 0) ? sum / count : 0.0;
    double variance =
        (count > 1) ? (sum_sq / count - mean * mean) * static_cast<double>(count) / (count - 1)
                    : 0.0;
    if (variance < 0.0) variance = 0.0;
    sigma = static_cast<float>(std::sqrt(std::max(1e-12, variance)));
  }

  template<typename PointRange, typename SeqOffsetsFloat>
  Quantized_Point_Range<PointRange, Metric> encode(
      const PointRange& data, const SeqOffsetsFloat& cloud_offsets_float) const {
#if !defined(TURBOQUANT_USE_IDENTITY_ROTATION)
    if (!rotator) {
      std::cerr << "TurboQuant::encode: rotator is null. Call train() first.\n";
      return Quantized_Point_Range<PointRange, Metric>();
    }
#endif
    if (cloud_offsets_float.size() < 2) {
      std::cerr << "TurboQuant::encode: need at least 2 cloud offsets.\n";
      return Quantized_Point_Range<PointRange, Metric>();
    }
    Quantized_Point_Range<PointRange, Metric> enc;
    enc.dim = padded_dim;
    enc.qjl_dim = qjl_dim;
    enc.n_points_raw_unpadded = data.size();

    const size_t n_clouds = (cloud_offsets_float.size() > 0) ? (cloud_offsets_float.size() - 1) : 0;
    enc.cloud_vec_offsets.resize(n_clouds + 1);

    size_t cur = 0;
    enc.cloud_vec_offsets[0] = 0;
    for (size_t c = 0; c < n_clouds; ++c) {
      const size_t start_f = static_cast<size_t>(cloud_offsets_float[c]);
      const size_t end_f = static_cast<size_t>(cloud_offsets_float[c + 1]);
      const size_t sz_vecs = (end_f - start_f) / dim;
      enc.cloud_vec_offsets[c] = cur;
      cur += sz_vecs;
    }
    enc.cloud_vec_offsets[n_clouds] = cur;
    enc.n_points_raw = cur;

    const size_t m_bytes = (qjl_dim + 7) / 8;
    const size_t stride = padded_dim + m_bytes + sizeof(float);
    enc.packed_codes.resize(enc.n_points_raw * stride, 0);

    if (n_clouds == 0) return enc;

    // Parallel encode: use thread_local workspace to avoid allocations
    struct EncodingWorkspace {
      std::vector<float> p_rot;
      std::vector<float> r;
      void ensure_size(size_t sz) {
        if (p_rot.size() != sz) {
          p_rot.resize(sz);
          r.resize(sz);
        }
      }
    };

    // Parallel over all vectors across all clouds
    parlay::parallel_for(0, enc.n_points_raw, [&](size_t vec_idx) {
      static thread_local EncodingWorkspace ws;
      ws.ensure_size(padded_dim);

      // Find which cloud this vector belongs to
      size_t c = 0;
      for (; c + 1 < n_clouds && enc.cloud_vec_offsets[c + 1] <= vec_idx; ++c) {
      }

      const size_t start_f = static_cast<size_t>(cloud_offsets_float[c]);
      const size_t end_f = static_cast<size_t>(cloud_offsets_float[c + 1]);
      const size_t start_vec_src = start_f / dim;
      const size_t start_vec_dst = enc.cloud_vec_offsets[c];
      const size_t i = vec_idx - start_vec_dst;
      const size_t src_idx = start_vec_src + i;
      const float* p = reinterpret_cast<const float*>(data.location(src_idx));
#if defined(TURBOQUANT_USE_IDENTITY_ROTATION)
      std::memcpy(ws.p_rot.data(), p, dim * sizeof(float));
      for (size_t d = dim; d < padded_dim; ++d)
        ws.p_rot[d] = 0.0f;
#else
      rotator->rotate(p, ws.p_rot.data());
#endif

      uint8_t* out = &enc.packed_codes[vec_idx * stride];
      uint8_t* base_out = out;
      uint8_t* qjl_out = out + padded_dim;

      float norm_r_sq = 0.0f;
      const float inv_sigma = (sigma > 1e-9f) ? (1.0f / sigma) : 1.0f;
      for (size_t d = 0; d < padded_dim; ++d) {
        float normalized = (ws.p_rot[d] - global_mean) * inv_sigma;
        // Binary search in Lloyd-Max thresholds for N(0,1)
        int idx = static_cast<int>(
            std::upper_bound(kLloydMaxThresholds, kLloydMaxThresholds + 255, normalized) -
            kLloydMaxThresholds);
        idx = std::max(0, std::min(255, idx));
        base_out[d] = static_cast<uint8_t>(idx);
        float approx = (kLloydMaxCentroids[idx] * sigma) + global_mean;
        ws.r[d] = ws.p_rot[d] - approx;
        norm_r_sq += ws.r[d] * ws.r[d];
      }

      // Optimized matrix-vector multiplication with SIMD
      for (size_t k = 0; k < qjl_dim; ++k) {
        float proj = 0.0f;
        const float* mat_row = &qjl_matrix[k * padded_dim];
        size_t d = 0;

#if defined(__AVX2__)
        __m256 sum_acc = _mm256_setzero_ps();
        for (; d + 8 <= padded_dim; d += 8) {
          __m256 mat_vals = _mm256_loadu_ps(&mat_row[d]);
          __m256 r_vals = _mm256_loadu_ps(&ws.r[d]);
          __m256 prod = _mm256_mul_ps(mat_vals, r_vals);
          sum_acc = _mm256_add_ps(sum_acc, prod);
        }

        // Horizontal sum
        alignas(32) float tmp_proj[8];
        _mm256_store_ps(tmp_proj, sum_acc);
        for (int i = 0; i < 8; ++i)
          proj += tmp_proj[i];
#endif

        // Scalar fallback for remaining elements
        for (; d < padded_dim; ++d) {
          proj += mat_row[d] * ws.r[d];
        }

        if (proj >= 0.0f) {
          qjl_out[k >> 3] |= static_cast<uint8_t>(1 << (k & 7));
        }
      }

      float norm_r = std::sqrt(norm_r_sq);
      std::memcpy(out + padded_dim + m_bytes, &norm_r, sizeof(float));
    });

    return enc;
  }

  template<typename PointRange>
  Quantized_Point_Range<PointRange, Metric> encode(const PointRange& data) const {
    std::vector<size_t> cloud_offsets_float;
    cloud_offsets_float.reserve(2);
    cloud_offsets_float.push_back(0);
    cloud_offsets_float.push_back(data.size() * dim);
    return encode(data, cloud_offsets_float);
  }

  // Primary overload: takes a pointer to float data
  Quantized_Query<Metric> quantize_query(const float* qptr) const {
#if !defined(TURBOQUANT_USE_IDENTITY_ROTATION)
    if (!rotator) {
      std::cerr << "TurboQuant::quantize_query: rotator is null. Call train() first.\n";
      return Quantized_Query<Metric>(0, 0);
    }
#endif
    Quantized_Query<Metric> qq(padded_dim, qjl_dim);
    std::vector<float> q_rot(padded_dim);
#if defined(TURBOQUANT_USE_IDENTITY_ROTATION)
    std::memcpy(q_rot.data(), qptr, dim * sizeof(float));
    for (size_t d = dim; d < padded_dim; ++d)
      q_rot[d] = 0.0f;
#else
    rotator->rotate(qptr, q_rot.data());
#endif

    // Stage 1 LUT: base_lut[d*256+c] = q_rot[d] * (centroid in data space); centroid =
    // kLloydMaxCentroids[c]*sigma + global_mean
    for (size_t d = 0; d < padded_dim; ++d) {
      float qd = q_rot[d];
      for (int c = 0; c < 256; ++c) {
        qq.base_lut[d * 256 + c] = qd * ((kLloydMaxCentroids[c] * sigma) + global_mean);
      }
    }

    // Optimized matrix-vector multiplication with SIMD
    for (size_t k = 0; k < qjl_dim; ++k) {
      float proj = 0.0f;
      const float* mat_row = &qjl_matrix[k * padded_dim];
      size_t d = 0;

#if defined(__AVX2__)
      __m256 sum_acc = _mm256_setzero_ps();
      for (; d + 8 <= padded_dim; d += 8) {
        __m256 mat_vals = _mm256_loadu_ps(&mat_row[d]);
        __m256 q_vals = _mm256_loadu_ps(&q_rot[d]);
        __m256 prod = _mm256_mul_ps(mat_vals, q_vals);
        sum_acc = _mm256_add_ps(sum_acc, prod);
      }

      // Horizontal sum
      alignas(32) float tmp[8];
      _mm256_store_ps(tmp, sum_acc);
      for (int i = 0; i < 8; ++i)
        proj += tmp[i];
#endif

      // Scalar fallback for remaining elements
      for (; d < padded_dim; ++d) {
        proj += mat_row[d] * q_rot[d];
      }

      qq.q_qjl[k] = proj;
    }

    return qq;
  }

  // Template overload for array-like types (but not pointers - those use the const float* overload
  // above)
  template<typename PointTy>
  typename std::enable_if<!std::is_pointer<PointTy>::value, Quantized_Query<Metric>>::type
  quantize_query(const PointTy& query) const {
    std::vector<float> tmp(dim);
    for (size_t i = 0; i < dim; ++i)
      tmp[i] = query[i];
    return quantize_query(tmp.data());
  }

  template<typename PointCloudTy>
  void quantize_query_batch(const PointCloudTy& query_cloud,
                            parlay::sequence<Quantized_Query<Metric>>& out_queries) const {
    const uint32_t num_q = query_cloud.size();
    const uint32_t dims = query_cloud.get_dims();
    const float* base = query_cloud.data();

    out_queries.clear();
    out_queries.reserve(num_q);
    for (uint32_t i = 0; i < num_q; ++i) {
      out_queries.emplace_back(quantize_query(base + static_cast<size_t>(i) * dims));
    }
  }

  void save(std::ofstream& out) const {
#if !defined(TURBOQUANT_USE_IDENTITY_ROTATION)
    if (!rotator) return;
#endif
    out.write(reinterpret_cast<const char*>(&dim), sizeof(dim));
    out.write(reinterpret_cast<const char*>(&padded_dim), sizeof(padded_dim));
    out.write(reinterpret_cast<const char*>(&qjl_dim), sizeof(qjl_dim));

#if !defined(TURBOQUANT_USE_IDENTITY_ROTATION)
    int rot_type_int = static_cast<int>(rotator_type);
    out.write(reinterpret_cast<const char*>(&rot_type_int), sizeof(rot_type_int));
    rotator->save(out);
#endif

    out.write(reinterpret_cast<const char*>(&sigma), sizeof(sigma));
    out.write(reinterpret_cast<const char*>(qjl_matrix.data()),
              qjl_dim * padded_dim * sizeof(float));
  }

  void load(std::ifstream& in) {
    in.read(reinterpret_cast<char*>(&dim), sizeof(dim));
    in.read(reinterpret_cast<char*>(&padded_dim), sizeof(padded_dim));
    in.read(reinterpret_cast<char*>(&qjl_dim), sizeof(qjl_dim));
#if !defined(TURBOQUANT_USE_IDENTITY_ROTATION)
    int rot_type_int = 0;
    in.read(reinterpret_cast<char*>(&rot_type_int), sizeof(rot_type_int));
    rotator_type = static_cast<rabitqlib::RotatorType>(rot_type_int);
    rotator.reset(rabitqlib::choose_rotator<float>(dim, rotator_type));
    if (rotator) rotator->load(in);
#endif

    qjl_matrix.resize(qjl_dim * padded_dim);

    in.read(reinterpret_cast<char*>(&sigma), sizeof(sigma));
    in.read(reinterpret_cast<char*>(&global_mean), sizeof(global_mean));
    in.read(reinterpret_cast<char*>(qjl_matrix.data()), qjl_dim * padded_dim * sizeof(float));
  }
};

}  // namespace turboquant_naive
}  // namespace mvsic