name: "Ablation: k per level"

datasets:
  # - name: arguana
  #   path: data/beir/arguana
  #   results: results/beir/arguana
  - name: scidocs
    path: data/beir/scidocs
    results: results/beir/scidocs
  # - name: quora
  #   path: data/beir/quora
  #   results: results/beir/quora
  # # - name: science_forum
  # #   path: data/lotte/dev/science
  # #   results: results/lotte/dev/science_forum
  # - name: tatdqa
  #   path: data/vidore/tatdqa
  #   results: results/vidore/tatdqa

indices:
  - name: mvivf
    build_configs:
      - name: mvivf_500
        params:
          k_per_level: 0
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
      - name: mvivf_2_500
        params:
          k_per_level: 2
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
      - name: mvivf_10_500
        params:
          k_per_level: 10
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
      - name: mvivf_20_500
        params:
          k_per_level: 20
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
      - name: mvivf_50_500
        params:
          k_per_level: 50
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
      - name: mvivf_100_500
        params:
          k_per_level: 100
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
      - name: mvivf_150_500
        params:
          k_per_level: 150
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
      - name: mvivf_200_500
        params:
          k_per_level: 200
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
              k: [10]
              config:
                - {name: "", num_rerank: 0}