dataset:
  name: arguana
  path: data/beir/arguana
  results: results/beir/arguana

indices:
  - name: mvivf
    build_configs:
      - name: mvivf_500  # A unique, human-readable name for this build
        rebuild: false # True/False
        build_only: false # True/False
        params:
          k_per_level: 0 # Default 0: Avg num embs
          max_leaf_size: 500
        search_configs:
          - name: k=10 # Name for this specific search experiment
            # The script will generate the Cartesian product of all parameter lists here.
            append: false
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
              k: [10]
              config: 
                - {name: "", num_rerank: 0}

      - name: mvivf_pq_500  # A unique, human-readable name for this build
        rebuild: false # True/False
        build_only: false # True/False
        params:
          k_per_level: 0 # Default 0: Avg num embs
          max_leaf_size: 500
          pq_enabled: true
        # Search configurations to run *only* on the 'mvivf_500' index.
        search_configs:
          - name: k=10 # Name for this specific search experiment
            # The script will generate the Cartesian product of all parameter lists here.
            append: false
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
              k: [10]
              config: 
                - {name: "", num_rerank: 100}

  - name: muvera
    build_configs:
      - name: muvera_2560
        rebuild: false
        params:
          d_fde: 2560 # FDE dim [2560, 5120]
        search_configs:
          - name: k=10
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512]
              k: [10]
              config: 
                - {name: "", num_rerank: 80}

  - name: mpool
    build_configs:
      - name: mpool
        rebuild: false
        params:
        search_configs:
          - name: k=10
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512]
              k: [10]
              config: 
                - {name: "", num_rerank: 80}

  - name: vamana
    build_configs:
      - name: vamana
        rebuild: false
        params:
        search_configs:
          - name: k=10
            append: false
            params:
              L: [16, 32, 64, 128, 256, 512]
              k: [10]
              config: 
                - {name: "", num_rerank: 0}

  - name: fastplaid
    build_configs:
      - name: fastplaid
        rebuild: false
        params:
          nbits: 4
        search_configs:
          - name: k=10
            append: false
            params:
              n_ivf_probe: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
              k: [10]
              config: 
                - {name: "", n_full_scores: 4096}