name: "BEIR Datasets"

datasets:
  - name: nfcorpus
    path: data/beir/nfcorpus
    results: results/beir/nfcorpus
  - name: scifact
    path: data/beir/scifact
    results: results/beir/scifact
  - name: arguana
    path: data/beir/arguana
    results: results/beir/arguana
  - name: scidocs
    path: data/beir/scidocs
    results: results/beir/scidocs
  - name: fiqa
    path: data/beir/fiqa
    results: results/beir/fiqa
  - name: quora
    path: data/beir/quora
    results: results/beir/quora
  # - name: nq
  #   path: data/beir/nq
  #   results: results/beir/nq
  # - name: hotpotqa
  #   path: data/beir/hotpotqa
  #   results: results/beir/hotpotqa

indices:
  - name: mvivf
    build_configs:
      - name: mvivf_500
        rebuild: True
        params:
          k_per_level: 0
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
          - name: k=100
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [100]
              config:
                - {name: "", num_rerank: 0}
  
  - name: muvera
    build_configs:
      - name: muvera_2560
        rebuild: True
        params:
          d_fde: 2560 # FDE dim [2560, 5120]
          pq_method: 0
        search_configs:
          - name: k=10
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                - {name: "nr10", num_rerank: 10, norerank: True}
                - {name: "nr50", num_rerank: 50}
                - {name: "nr500", num_rerank: 500}
                - {name: "nr5000", num_rerank: 5000}
          - name: k=100
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [100]
              config:
                - {name: "nr100", num_rerank: 100, norerank: True}
                - {name: "nr500", num_rerank: 500}
                - {name: "nr5000", num_rerank: 5000}

  - name: svh_ivf
    build_configs:
      - name: svh_ivf_500
        params:
          k_per_level: 0
          max_leaf_size: 500
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                - {name: "nr10", num_rerank: 10, norerank: True}
                - {name: "nr50", num_rerank: 50}
                - {name: "nr500", num_rerank: 500}
                - {name: "nr5000", num_rerank: 5000}
          - name: k=100
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [100]
              config:
                - {name: "nr100", num_rerank: 100, norerank: True}
                - {name: "nr500", num_rerank: 500}
                - {name: "nr5000", num_rerank: 5000}

  - name: vamana
    build_configs:
      - name: vamana_200
        params:
          R: 200
          pq_method: 0
        search_configs:
          - name: k=10
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
          - name: k=100
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [100]
              config:
                - {name: "", num_rerank: 0}