name: "BEIR Datasets w/ Product Quantization"

datasets:
  - name: nfcorpus
    path: data/beir/nfcorpus
    results: results/beir/nfcorpus
  - name: scifact
    path: data/beir/scifact
    results: results/beir/scifact
  - name: arguana
    path: data/beir/arguana
    results: results/beir/arguana
  - name: scidocs
    path: data/beir/scidocs
    results: results/beir/scidocs
  - name: fiqa
    path: data/beir/fiqa
    results: results/beir/fiqa
  # - name: quora
  #   path: data/beir/quora
  #   results: results/beir/quora
  # - name: nq
  #   path: data/beir/nq
  #   results: results/beir/nq
  # - name: hotpotqa
  #   path: data/beir/hotpotqa
  #   results: results/beir/hotpotqa

indices:
  - name: mvivf
    build_configs:
      - name: mvivf_500_pq_16_64
        params:
          k_per_level: 0
          max_leaf_size: 500
          pq_method: 1 # [None, PQ, RabitQ, ScaNN]
          block_size: 64
          num_clusters_per_block: 16
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                - {name: "nr40", num_rerank: 40}
                - {name: "nr160", num_rerank: 160}
                - {name: "nr640", num_rerank: 640}
                - {name: "nr2560", num_rerank: 2560}
      - name: mvivf_500_rabitq_2
        params:
          k_per_level: 0
          max_leaf_size: 500
          pq_method: 2 # [None, PQ, RabitQ, ScaNN]
          rabitq_bits: 2
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                - {name: "nr40", num_rerank: 40}
                # - {name: "nr160", num_rerank: 160}
                # - {name: "nr640", num_rerank: 640}
                # - {name: "nr2560", num_rerank: 2560}
  
  - name: muvera
    build_configs:
      - name: muvera_2560_pq_256_8
        params:
          d_fde: 2560 # FDE dim [2560, 5120]
          pq_method: 1
          block_size: 8
          num_clusters_per_block: 256
        search_configs:
          - name: k=10
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                # - {name: "nr40", num_rerank: 40}
                # - {name: "nr160", num_rerank: 160}
                # - {name: "nr640", num_rerank: 640}
                - {name: "nr2560", num_rerank: 2560}
      - name: muvera_2560_rabitq_2
        params:
          d_fde: 2560 # FDE dim [2560, 5120]
          pq_method: 2
          rabitq_bits: 2
        search_configs:
          - name: k=10
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                # - {name: "nr40", num_rerank: 40}
                # - {name: "nr160", num_rerank: 160}
                # - {name: "nr640", num_rerank: 640}
                - {name: "nr2560", num_rerank: 2560}