name: "ViDoRe Datasets"

datasets:
  - name: docvqa
    path: data/vidore/docvqa
    results: results/vidore/docvqa
  - name: infovqa
    path: data/vidore/infovqa
    results: results/vidore/infovqa
  - name: tatdqa
    path: data/vidore/tatdqa
    results: results/vidore/tatdqa
  - name: arxivqa
    path: data/vidore/arxivqa
    results: results/vidore/arxivqa
  - name: tabfquad
    path: data/vidore/tabfquad
    results: results/vidore/tabfquad
  # - name: synth_healthcare
  #   path: data/vidore/synth_healthcare
  #   results: results/vidore/synth_healthcare
  # - name: synth_ai
  #   path: data/vidore/synth_ai
  #   results: results/vidore/synth_ai
  # - name: shiftproject
  #   path: data/vidore/shiftproject
  #   results: results/vidore/shiftproject


indices:
  - name: mvivf
    build_configs:
      - name: mvivf_500_100
        params:
          k_per_level: 0
          max_leaf_size: 500
          s: 100
          pq_method: 0 # [None, PQ, RabitQ, ScaNN]
        search_configs:
          - name: k=10
            params:
              nprobes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                - {name: "", num_rerank: 0}
  
  - name: muvera
    build_configs:
      - name: muvera_2560
        params:
          d_fde: 2560 # FDE dim [2560, 5120]
          pq_method: 0
        search_configs:
          - name: k=10
            params:
              L: [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
              k: [10]
              config:
                - {name: "nr40", num_rerank: 40}
                - {name: "nr160", num_rerank: 160}
                - {name: "nr640", num_rerank: 640}
                - {name: "nr2560", num_rerank: 2560}